export const CITY_COORDINATES: Record<string, { lat: number; lng: number; radius: number; isSmall?: boolean }> = {
  // Orașe mari
  'Cluj-Napoca':     { lat: 46.7712, lng: 23.6236, radius: 15000 },
  'Brașov':          { lat: 45.6427, lng: 25.5887, radius: 15000 },
  'Sibiu':           { lat: 45.7983, lng: 24.1256, radius: 12000 },
  'Târgu Mureș':     { lat: 46.5386, lng: 24.5575, radius: 12000 },
  'Alba Iulia':      { lat: 46.0669, lng: 23.5799, radius: 10000 },
  'Bistrița':        { lat: 47.1333, lng: 24.5000, radius: 10000 },
  'Deva':            { lat: 45.8833, lng: 22.9000, radius: 8000  },
  'Sighișoara':      { lat: 46.2197, lng: 24.7937, radius: 6000  },
  'Sfântu Gheorghe': { lat: 45.8670, lng: 25.7870, radius: 8000  },
  'Miercurea Ciuc':  { lat: 46.3578, lng: 25.8024, radius: 8000  },
  'Zalău':           { lat: 47.1897, lng: 23.0569, radius: 8000  },
  'Turda':           { lat: 46.5667, lng: 23.7833, radius: 6000  },
  'Oradea':          { lat: 47.0458, lng: 21.9189, radius: 15000 },
  'Timișoara':       { lat: 45.7489, lng: 21.2087, radius: 18000 },
  'Arad':            { lat: 46.1700, lng: 21.3150, radius: 12000 },
  'București':       { lat: 44.4268, lng: 26.1025, radius: 25000 },
  'Iași':            { lat: 47.1585, lng: 27.6014, radius: 15000 },
  'Constanța':       { lat: 44.1765, lng: 28.6480, radius: 15000 },
  'Craiova':         { lat: 44.3302, lng: 23.7949, radius: 12000 },
  'Ploiești':        { lat: 44.9365, lng: 26.0226, radius: 12000 },
  'Galați':          { lat: 45.4353, lng: 28.0080, radius: 12000 },
  'Bacău':           { lat: 46.5670, lng: 26.9146, radius: 12000 },
  'Suceava':         { lat: 47.6520, lng: 26.2547, radius: 10000 },
  'Pitești':         { lat: 44.8565, lng: 24.8692, radius: 10000 },
  'Baia Mare':       { lat: 47.6567, lng: 23.5681, radius: 10000 },
  'Satu Mare':       { lat: 47.7914, lng: 22.8844, radius: 10000 },
  'Brăila':          { lat: 45.2692, lng: 27.9574, radius: 10000 },
  'Râmnicu Vâlcea':  { lat: 45.0996, lng: 24.3690, radius: 8000  },
  'Buzău':           { lat: 45.1500, lng: 26.8167, radius: 8000  },
  'Focșani':         { lat: 45.6969, lng: 27.1876, radius: 8000  },
  'Târgu Jiu':       { lat: 45.0333, lng: 23.2833, radius: 8000  },
  'Tulcea':          { lat: 45.1787, lng: 28.8042, radius: 8000  },
  'Dej':             { lat: 47.1508, lng: 23.8697, radius: 6000  },
  'Piatra Neamț':    { lat: 46.9258, lng: 26.3717, radius: 8000  },
  // Orașe mici – concurență ZERO
  'Câmpia Turzii':   { lat: 46.5573, lng: 23.8831, radius: 5000, isSmall: true },
  'Gherla':          { lat: 47.0333, lng: 23.9000, radius: 5000, isSmall: true },
  'Huedin':          { lat: 46.8833, lng: 22.9000, radius: 4000, isSmall: true },
  'Florești CJ':     { lat: 46.7430, lng: 23.5116, radius: 4000, isSmall: true },
  'Săcele':          { lat: 45.6167, lng: 25.7000, radius: 5000, isSmall: true },
  'Codlea':          { lat: 45.7000, lng: 25.4500, radius: 4000, isSmall: true },
  'Zărnești':        { lat: 45.5500, lng: 25.3333, radius: 4000, isSmall: true },
  'Râșnov':          { lat: 45.5858, lng: 25.4558, radius: 4000, isSmall: true },
  'Predeal':         { lat: 45.5058, lng: 25.5783, radius: 3000, isSmall: true },
  'Cisnădie':        { lat: 45.7083, lng: 24.1550, radius: 4000, isSmall: true },
  'Avrig':           { lat: 45.7083, lng: 24.3667, radius: 3000, isSmall: true },
  'Reghin':          { lat: 46.7756, lng: 24.7025, radius: 5000, isSmall: true },
  'Luduș':           { lat: 46.4769, lng: 24.1092, radius: 4000, isSmall: true },
  'Mediaș':          { lat: 46.1622, lng: 24.3519, radius: 6000, isSmall: true },
  'Sebeș':           { lat: 45.9567, lng: 23.5675, radius: 5000, isSmall: true },
  'Blaj':            { lat: 46.1750, lng: 23.9167, radius: 4000, isSmall: true },
  'Beiuș':           { lat: 46.6706, lng: 22.3525, radius: 4000, isSmall: true },
  'Salonta':         { lat: 46.7992, lng: 21.6503, radius: 4000, isSmall: true },
  'Marghita':        { lat: 47.3503, lng: 22.3228, radius: 4000, isSmall: true },
  'Lugoj':           { lat: 45.6881, lng: 21.9036, radius: 6000, isSmall: true },
  'Deta':            { lat: 45.3972, lng: 21.2250, radius: 3000, isSmall: true },
  'Petroșani':       { lat: 45.4178, lng: 23.3644, radius: 5000, isSmall: true },
  'Orăștie':         { lat: 45.8333, lng: 23.2000, radius: 4000, isSmall: true },
  'Brad':            { lat: 46.1267, lng: 22.7817, radius: 3000, isSmall: true },
  'Sinaia':          { lat: 45.3500, lng: 25.5500, radius: 4000, isSmall: true },
  'Bușteni':         { lat: 45.4000, lng: 25.5333, radius: 3000, isSmall: true },
  'Câmpina':         { lat: 45.1167, lng: 25.7333, radius: 5000, isSmall: true },
  'Mangalia':        { lat: 43.8122, lng: 28.5847, radius: 5000, isSmall: true },
  'Eforie Nord':     { lat: 44.0608, lng: 28.6308, radius: 3000, isSmall: true },
  'Năvodari':        { lat: 44.3228, lng: 28.6164, radius: 5000, isSmall: true },
  'Câmpulung Moldovenesc': { lat: 47.5272, lng: 25.5592, radius: 4000, isSmall: true },
  'Rădăuți':         { lat: 47.8453, lng: 25.9197, radius: 5000, isSmall: true },
  'Vatra Dornei':    { lat: 47.3556, lng: 25.3600, radius: 4000, isSmall: true },
  'Târgu Neamț':     { lat: 47.2000, lng: 26.3667, radius: 4000, isSmall: true },
  'Sighetul Marmației': { lat: 47.9289, lng: 23.8889, radius: 6000, isSmall: true },
  'Curtea de Argeș': { lat: 45.1381, lng: 24.6758, radius: 4000, isSmall: true },
  'Câmpulung':       { lat: 45.2653, lng: 25.0486, radius: 5000, isSmall: true },
  'Drăgășani':       { lat: 44.6622, lng: 24.2664, radius: 4000, isSmall: true },
  'Horezu':          { lat: 45.1036, lng: 23.9903, radius: 3000, isSmall: true },
}

export const JUDETE: Record<string, string[]> = {
  'Cluj':       ['Cluj-Napoca', 'Turda', 'Dej', 'Câmpia Turzii', 'Gherla', 'Huedin', 'Florești CJ'],
  'Brașov':     ['Brașov', 'Săcele', 'Codlea', 'Zărnești', 'Râșnov', 'Predeal'],
  'Sibiu':      ['Sibiu', 'Mediaș', 'Cisnădie', 'Avrig'],
  'Mureș':      ['Târgu Mureș', 'Reghin', 'Luduș', 'Sighișoara'],
  'Alba':       ['Alba Iulia', 'Sebeș', 'Blaj'],
  'Bihor':      ['Oradea', 'Beiuș', 'Salonta', 'Marghita'],
  'Timiș':      ['Timișoara', 'Lugoj', 'Deta'],
  'Hunedoara':  ['Deva', 'Petroșani', 'Orăștie', 'Brad'],
  'Prahova':    ['Ploiești', 'Sinaia', 'Bușteni', 'Câmpina'],
  'Constanța':  ['Constanța', 'Mangalia', 'Eforie Nord', 'Năvodari'],
  'Suceava':    ['Suceava', 'Câmpulung Moldovenesc', 'Rădăuți', 'Vatra Dornei'],
  'Neamț':      ['Piatra Neamț', 'Târgu Neamț'],
  'Maramureș':  ['Baia Mare', 'Sighetul Marmației'],
  'Argeș':      ['Pitești', 'Curtea de Argeș', 'Câmpulung'],
  'Vâlcea':     ['Râmnicu Vâlcea', 'Drăgășani', 'Horezu'],
  'Ilfov/Buc':  ['București'],
  'Iași':       ['Iași'],
  'Galați':     ['Galați', 'Brăila'],
  'Bacău':      ['Bacău'],
  'Satu Mare':  ['Satu Mare'],
  'Bistrița':   ['Bistrița'],
  'Arad':       ['Arad'],
  'Buzău':      ['Buzău'],
  'Focșani':    ['Focșani'],
  'Craiova':    ['Craiova', 'Târgu Jiu'],
  'Tulcea':     ['Tulcea'],
}

export const BUSINESS_CATEGORIES: Record<string, string> = {
  restaurant:       'Restaurant / Cafenea',
  dentist:          'Cabinet Stomatologic',
  beauty_salon:     'Salon de Înfrumusețare',
  car_repair:       'Service Auto',
  plumber:          'Instalator / Sanitare',
  electrician:      'Electrician',
  lawyer:           'Cabinet Avocat',
  accounting:       'Contabilitate',
  lodging:          'Hotel / Pensiune',
  hair_care:        'Frizerie / Coafor',
  doctor:           'Cabinet Medical',
  gym:              'Sală de Fitness',
  florist:          'Florărie',
  bakery:           'Brutărie / Patiserie',
  veterinary_care:  'Cabinet Veterinar',
  moving_company:   'Firmă Mutări',
  photographer:     'Studio Foto / Video',
  physiotherapist:  'Cabinet Fizioterapie',
  car_wash:         'Spălătorie Auto',
  painter:          'Constructor / Zugrav',
}

// Categorii cu conversie maximă – testate
export const HIGH_CONVERSION_CATEGORIES = [
  'beauty_salon',
  'lodging',
  'hair_care',
  'bakery',
  'car_repair',
  'dentist',
  'photographer',
  'restaurant',
]

export interface PainPoint {
  pain: string
  gain: string
  hook: string
  urgency: string
  waHook: string // hook specific pentru WhatsApp (ultra-scurt, emoțional)
}

export const CATEGORY_PAIN_POINTS: Record<string, PainPoint> = {
  restaurant: {
    pain: 'clienții nu vă pot vedea meniul online, nu pot rezerva o masă și nu vă găsesc pe Google',
    gain: 'rezervări online, meniu digital, prezență pe Google și TripAdvisor',
    hook: '72% dintre oameni caută restaurante online înainte să iasă din casă',
    urgency: 'restaurantele cu site primesc cu 40% mai multe rezervări în weekend-urile aglomerate',
    waHook: 'clienții vă caută online și nu vă găsesc',
  },
  dentist: {
    pain: 'pacienții noi nu vă găsesc și merg la concurența care are site modern',
    gain: 'programări online 24/7, imagine profesională, pacienți noi lunar',
    hook: '85% din pacienți verifică online înainte de a alege un stomatolog',
    urgency: 'cabinetele cu site primesc 8-12 programări noi pe lună din online',
    waHook: 'pacienți noi din Google în fiecare lună',
  },
  beauty_salon: {
    pain: 'clienții vă caută pe Instagram dar nu găsesc prețurile sau o modalitate să rezerve',
    gain: 'programări online, galerie foto cu lucrările voastre, mai puține telefoane',
    hook: 'femeile caută saloane pe Google, nu în cartea de telefoane',
    urgency: 'salonul din vecinătate are deja site și apare primul în căutări',
    waHook: 'rezervări online fără telefoane și clienți noi zilnic',
  },
  car_repair: {
    pain: 'când mașina se strică, oamenii caută urgent pe Google – dacă nu ești acolo, mergi la concurență',
    gain: 'clienți noi din Google, listă de servicii și prețuri, credibilitate',
    hook: '"service auto [orașul tău]" e căutat de mii de ori pe lună',
    urgency: 'service-urile cu site apar primele în Google Maps și primesc 3x mai multe apeluri',
    waHook: 'să apăreați primii pe Google când cineva caută service',
  },
  plumber: {
    pain: 'când țevile se sparg la ora 10 noaptea, clientul caută pe Google – nu în agendă',
    gain: 'apeluri urgente non-stop, zonă de acoperire clară, recenzii verificate',
    hook: '"instalator urgență [oraș]" e una din cele mai căutate fraze locale',
    urgency: 'instalatorii cu site sunt contactați de 4x mai mulți clienți noi lunar',
    waHook: 'apeluri urgente din Google când cineva caută instalator',
  },
  electrician: {
    pain: 'clienții nu știu ce servicii oferi, la ce prețuri și dacă ești disponibil',
    gain: 'lead-uri noi zilnic, portofoliu de lucrări, zonă de activitate vizibilă',
    hook: 'căutările pentru electricieni locali au crescut cu 60% în ultimii 2 ani',
    urgency: 'fără site ești invizibil pentru 90% din clienții potențiali din zonă',
    waHook: 'clienți noi din zona voastră prin Google',
  },
  lawyer: {
    pain: 'clienții caută avocați pe Google, nu din gură în gură – fără site, pierdeți clienți zilnic',
    gain: 'consultanță online, credibilitate profesională, clienți noi din zonă',
    hook: '68% din români caută avocați online înainte de primul contact',
    urgency: 'cabinetele cu site obțin 5-10 consultanțe noi pe lună doar din prezența online',
    waHook: 'clienți noi care caută avocat online',
  },
  accounting: {
    pain: 'firmele tinere caută contabili pe Google – fără site nu existați pentru ele',
    gain: 'clienți noi lunar, imagine profesională, formulare de contact',
    hook: 'startup-urile și firmele noi își caută contabilul exclusiv online',
    urgency: 'sezonul declarațiilor e acum – firmele caută contabili chiar în această perioadă',
    waHook: 'firme noi care caută contabil pe Google',
  },
  lodging: {
    pain: 'turiștii rezervă pe Booking.com și plătiți comision mare – un site propriu vă scapă de asta',
    gain: 'rezervări directe fără comision, galerie foto profesională, pachete speciale',
    hook: '20-30% economii din comisioane dacă aveți rezervări directe',
    urgency: 'sezonul turistic se apropie – turiștii își planifică vacanțele chiar acum',
    waHook: 'rezervări directe fără comision Booking.com',
  },
  hair_care: {
    pain: 'clienții vin la recomandare, dar rata de clienți noi e mică fără prezență online',
    gain: 'rezervări online, galerie cu stiluri, fidelizare clienți existenți',
    hook: 'salonul cu site apare în top 3 Google Maps când cineva caută "coafor [orașul tău]"',
    urgency: 'poziția în Google se construiește în timp – cu cât începi mai devreme, cu atât ești mai sus',
    waHook: 'rezervări online și clienți noi',
  },
  doctor: {
    pain: 'pacienții noi nu știu ce specialități oferi, programul sau cum te contactează',
    gain: 'programări online, listă de servicii, credibilitate și încredere',
    hook: '90% din pacienți caută online informații despre medic înainte de prima vizită',
    urgency: 'cabinetele cu site profesional sunt percepute ca mai competente și mai organizate',
    waHook: 'programări online și pacienți noi lunar',
  },
  gym: {
    pain: 'oamenii caută săli de sport pe Google – fără site, merg la sala de alături care apare online',
    gain: 'abonamente online, program clase, galerie echipamente',
    hook: 'căutările pentru săli de sport sunt la maxim tot sezonul',
    urgency: 'fiecare zi fără site e o zi cu abonamente pierdute',
    waHook: 'abonamente noi și vizibilitate online',
  },
  florist: {
    pain: 'de 8 Martie și nunți, oamenii comandă flori online – ești acolo?',
    gain: 'comenzi online, catalog produse, livrare în oraș',
    hook: 'florile sunt unul din cele mai cumpărate cadouri online în România',
    urgency: '8 Martie și sezonul nunților aduc cel mai mult trafic online pentru florării',
    waHook: 'comenzi online pentru nunți și ocazii',
  },
  bakery: {
    pain: 'comenzile de tort pentru evenimente se fac tot mai mult online, nu telefonic',
    gain: 'comenzi torturi aniversare și evenimente, catalog produse, program vizibil',
    hook: 'căutările pentru "tort comandă [oraș]" sunt în continuă creștere',
    urgency: 'sezoanele de comunioane și nunți sunt aproape – comenzile vin online',
    waHook: 'comenzi torturi și produse online de Paști',
  },
  veterinary_care: {
    pain: 'proprietarii de animale caută veterinar pe Google când e urgență',
    gain: 'programări online, urgențe 24/7, clienți noi fideli',
    hook: 'numărul de animale de companie din România a crescut cu 30% în ultimii ani',
    urgency: 'clinicile veterinare cu site primesc 3x mai multe programări noi',
    waHook: 'programări online și clienți noi urgent',
  },
  photographer: {
    pain: 'mirii caută fotograf online, nu din recomandări – fără portofoliu web pierdeți contracte',
    gain: 'portofoliu online 24/7, cereri de la mirei, pachetele și prețurile vizibile',
    hook: 'sezonul de nunți 2025 e la maxim – mirii rezervă cu 6-12 luni înainte',
    urgency: 'fiecare nuntă pe care o pierdeți e 1000-3000 EUR lăsați pe masă',
    waHook: 'portofoliu online și cereri de la mirei',
  },
  moving_company: {
    pain: 'clienții caută firmă de mutări urgent pe Google – fără site ești invizibil',
    gain: 'cereri de ofertă online din zonă, liste de servicii, credibilitate',
    hook: 'mutările sunt planificate online în 80% din cazuri',
    urgency: 'primăvara și vara = vârf de sezaon pentru mutări',
    waHook: 'cereri de ofertă online din zona voastră',
  },
  physiotherapist: {
    pain: 'pacienții caută fizioterapeut pe Google după recomandarea medicului',
    gain: 'programări online, lista de servicii și prețuri, credibilitate',
    hook: 'cererea pentru fizioterapie a crescut cu 40% post-pandemic',
    urgency: 'cabinetele cu site sunt pline – cele fără site au locuri libere',
    waHook: 'programări online și pacienți noi',
  },
  car_wash: {
    pain: 'clienții caută spălătorie pe Google Maps când sunt în zonă',
    gain: 'vizibilitate pe Google Maps, servicii și prețuri afișate, recenzii',
    hook: '"spălătorie auto [oraș]" e căutat zilnic de sute de ori',
    urgency: 'primăvara = vârf de sezon pentru spălătorii',
    waHook: 'clienți noi care caută spălătorie pe Google',
  },
  painter: {
    pain: 'constructorii și zugravii fără site pierd contracte mari de renovare',
    gain: 'portofoliu lucrări, cereri de ofertă online, credibilitate',
    hook: 'renovările se caută online – "zugrav [oraș]" are mii de căutări lunar',
    urgency: 'sezonul construcțiilor e acum – fiecare săptămână fără site = bani pierduți',
    waHook: 'cereri de ofertă online pentru renovări',
  },
  default: {
    pain: 'clienții potențiali nu vă pot găsi online și merg la concurența care are prezență web',
    gain: 'vizibilitate online 24/7, clienți noi în fiecare lună, imagine profesională',
    hook: '97% din consumatori caută servicii locale pe internet înainte să cumpere',
    urgency: 'fiecare zi fără website e o zi în care clienții merg la concurența ta',
    waHook: 'clienți noi din Google zilnic',
  },
}
